#!/usr/bin/python
print('Content-type: text/html\n\n')

import cgi
import cgitb; cgitb.enable()
import sqlite3

mydb = 'test.db'
conn = sqlite3.connect(mydb)
cursor = conn.cursor()

print('start inserting data into Classes table<br />')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10EN1")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10EN2")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10EN3")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10EN4")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10MS1")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10MS2")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10MS3")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10MS4")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10GY1")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10CE2")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10HY3")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10GP1")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10CH1")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10BY2")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10PH3")''')
cursor.execute('''INSERT INTO Classes (ID) VALUES ("10APH4")''')
print('finish inserting data into Classes table<br />')
print('start inserting data into Enrolments table<br />')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (0, 169, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (1, 169, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (2, 169, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (3, 169, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (4, 135, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (5, 135, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (6, 135, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (7, 135, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (8, 138, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (9, 138, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (10, 138, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (11, 138, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (12, 249, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (13, 249, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (14, 249, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (15, 249, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (16, 229, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (17, 229, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (18, 229, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (19, 229, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (20, 299, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (21, 299, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (22, 299, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (23, 299, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (24, 393, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (25, 393, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (26, 393, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (27, 393, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (28, 103, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (29, 103, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (30, 103, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (31, 103, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (32, 397, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (33, 397, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (34, 397, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (35, 397, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (36, 226, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (37, 226, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (38, 226, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (39, 226, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (40, 367, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (41, 367, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (42, 367, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (43, 367, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (44, 156, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (45, 156, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (46, 156, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (47, 156, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (48, 344, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (49, 344, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (50, 344, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (51, 344, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (52, 228, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (53, 228, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (54, 228, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (55, 228, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (56, 333, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (57, 333, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (58, 333, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (59, 333, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (60, 272, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (61, 272, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (62, 272, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (63, 272, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (64, 370, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (65, 370, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (66, 370, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (67, 370, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (68, 213, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (69, 213, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (70, 213, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (71, 213, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (72, 239, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (73, 239, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (74, 239, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (75, 239, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (76, 231, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (77, 231, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (78, 231, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (79, 231, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (80, 172, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (81, 172, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (82, 172, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (83, 172, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (84, 237, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (85, 237, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (86, 237, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (87, 237, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (88, 309, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (89, 309, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (90, 309, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (91, 309, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (92, 250, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (93, 250, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (94, 250, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (95, 250, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (96, 290, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (97, 290, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (98, 290, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (99, 290, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (100, 383, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (101, 383, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (102, 383, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (103, 383, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (104, 265, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (105, 265, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (106, 265, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (107, 265, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (108, 356, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (109, 356, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (110, 356, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (111, 356, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (112, 374, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (113, 374, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (114, 374, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (115, 374, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (116, 115, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (117, 115, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (118, 115, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (119, 115, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (120, 324, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (121, 324, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (122, 324, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (123, 324, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (124, 162, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (125, 162, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (126, 162, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (127, 162, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (128, 306, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (129, 306, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (130, 306, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (131, 306, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (132, 276, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (133, 276, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (134, 276, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (135, 276, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (136, 391, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (137, 391, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (138, 391, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (139, 391, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (140, 268, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (141, 268, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (142, 268, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (143, 268, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (144, 107, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (145, 107, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (146, 107, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (147, 107, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (148, 363, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (149, 363, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (150, 363, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (151, 363, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (152, 267, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (153, 267, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (154, 267, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (155, 267, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (156, 330, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (157, 330, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (158, 330, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (159, 330, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (160, 282, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (161, 282, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (162, 282, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (163, 282, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (164, 227, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (165, 227, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (166, 227, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (167, 227, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (168, 278, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (169, 278, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (170, 278, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (171, 278, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (172, 313, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (173, 313, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (174, 313, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (175, 313, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (176, 258, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (177, 258, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (178, 258, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (179, 258, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (180, 337, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (181, 337, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (182, 337, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (183, 337, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (184, 136, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (185, 136, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (186, 136, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (187, 136, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (188, 148, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (189, 148, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (190, 148, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (191, 148, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (192, 140, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (193, 140, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (194, 140, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (195, 140, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (196, 192, "10EN1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (197, 192, "10EN2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (198, 192, "10EN3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (199, 192, "10EN4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (200, 398, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (201, 398, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (202, 398, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (203, 398, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (204, 386, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (205, 386, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (206, 386, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (207, 386, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (208, 128, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (209, 128, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (210, 128, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (211, 128, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (212, 164, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (213, 164, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (214, 164, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (215, 164, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (216, 149, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (217, 149, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (218, 149, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (219, 149, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (220, 327, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (221, 327, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (222, 327, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (223, 327, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (224, 384, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (225, 384, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (226, 384, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (227, 384, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (228, 252, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (229, 252, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (230, 252, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (231, 252, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (232, 319, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (233, 319, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (234, 319, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (235, 319, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (236, 175, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (237, 175, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (238, 175, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (239, 175, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (240, 318, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (241, 318, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (242, 318, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (243, 318, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (244, 210, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (245, 210, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (246, 210, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (247, 210, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (248, 280, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (249, 280, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (250, 280, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (251, 280, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (252, 362, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (253, 362, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (254, 362, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (255, 362, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (256, 199, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (257, 199, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (258, 199, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (259, 199, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (260, 168, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (261, 168, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (262, 168, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (263, 168, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (264, 206, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (265, 206, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (266, 206, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (267, 206, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (268, 315, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (269, 315, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (270, 315, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (271, 315, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (272, 132, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (273, 132, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (274, 132, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (275, 132, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (276, 152, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (277, 152, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (278, 152, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (279, 152, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (280, 225, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (281, 225, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (282, 225, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (283, 225, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (284, 205, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (285, 205, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (286, 205, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (287, 205, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (288, 215, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (289, 215, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (290, 215, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (291, 215, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (292, 233, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (293, 233, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (294, 233, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (295, 233, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (296, 291, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (297, 291, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (298, 291, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (299, 291, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (300, 113, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (301, 113, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (302, 113, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (303, 113, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (304, 186, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (305, 186, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (306, 186, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (307, 186, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (308, 375, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (309, 375, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (310, 375, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (311, 375, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (312, 104, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (313, 104, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (314, 104, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (315, 104, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (316, 271, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (317, 271, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (318, 271, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (319, 271, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (320, 279, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (321, 279, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (322, 279, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (323, 279, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (324, 358, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (325, 358, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (326, 358, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (327, 358, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (328, 212, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (329, 212, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (330, 212, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (331, 212, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (332, 369, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (333, 369, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (334, 369, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (335, 369, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (336, 274, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (337, 274, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (338, 274, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (339, 274, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (340, 345, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (341, 345, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (342, 345, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (343, 345, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (344, 388, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (345, 388, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (346, 388, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (347, 388, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (348, 154, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (349, 154, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (350, 154, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (351, 154, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (352, 373, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (353, 373, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (354, 373, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (355, 373, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (356, 394, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (357, 394, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (358, 394, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (359, 394, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (360, 141, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (361, 141, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (362, 141, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (363, 141, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (364, 262, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (365, 262, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (366, 262, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (367, 262, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (368, 399, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (369, 399, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (370, 399, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (371, 399, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (372, 352, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (373, 352, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (374, 352, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (375, 352, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (376, 188, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (377, 188, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (378, 188, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (379, 188, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (380, 389, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (381, 389, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (382, 389, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (383, 389, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (384, 217, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (385, 217, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (386, 217, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (387, 217, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (388, 283, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (389, 283, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (390, 283, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (391, 283, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (392, 142, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (393, 142, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (394, 142, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (395, 142, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (396, 100, "10MS1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (397, 100, "10MS2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (398, 100, "10MS3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (399, 100, "10MS4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (400, 119, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (401, 119, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (402, 119, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (403, 119, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (404, 256, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (405, 256, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (406, 256, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (407, 256, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (408, 211, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (409, 211, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (410, 211, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (411, 211, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (412, 224, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (413, 224, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (414, 224, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (415, 224, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (416, 116, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (417, 116, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (418, 116, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (419, 116, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (420, 163, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (421, 163, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (422, 163, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (423, 163, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (424, 246, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (425, 246, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (426, 246, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (427, 246, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (428, 331, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (429, 331, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (430, 331, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (431, 331, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (432, 177, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (433, 177, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (434, 177, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (435, 177, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (436, 253, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (437, 253, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (438, 253, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (439, 253, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (440, 260, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (441, 260, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (442, 260, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (443, 260, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (444, 300, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (445, 300, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (446, 300, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (447, 300, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (448, 218, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (449, 218, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (450, 218, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (451, 218, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (452, 332, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (453, 332, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (454, 332, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (455, 332, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (456, 326, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (457, 326, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (458, 326, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (459, 326, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (460, 270, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (461, 270, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (462, 270, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (463, 270, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (464, 343, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (465, 343, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (466, 343, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (467, 343, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (468, 281, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (469, 281, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (470, 281, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (471, 281, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (472, 118, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (473, 118, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (474, 118, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (475, 118, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (476, 351, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (477, 351, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (478, 351, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (479, 351, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (480, 350, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (481, 350, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (482, 350, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (483, 350, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (484, 153, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (485, 153, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (486, 153, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (487, 153, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (488, 312, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (489, 312, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (490, 312, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (491, 312, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (492, 320, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (493, 320, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (494, 320, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (495, 320, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (496, 121, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (497, 121, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (498, 121, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (499, 121, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (500, 179, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (501, 179, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (502, 179, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (503, 179, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (504, 359, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (505, 359, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (506, 359, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (507, 359, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (508, 214, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (509, 214, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (510, 214, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (511, 214, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (512, 303, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (513, 303, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (514, 303, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (515, 303, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (516, 167, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (517, 167, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (518, 167, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (519, 167, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (520, 317, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (521, 317, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (522, 317, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (523, 317, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (524, 134, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (525, 134, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (526, 134, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (527, 134, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (528, 354, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (529, 354, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (530, 354, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (531, 354, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (532, 158, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (533, 158, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (534, 158, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (535, 158, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (536, 347, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (537, 347, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (538, 347, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (539, 347, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (540, 151, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (541, 151, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (542, 151, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (543, 151, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (544, 314, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (545, 314, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (546, 314, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (547, 314, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (548, 385, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (549, 385, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (550, 385, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (551, 385, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (552, 263, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (553, 263, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (554, 263, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (555, 263, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (556, 381, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (557, 381, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (558, 381, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (559, 381, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (560, 114, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (561, 114, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (562, 114, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (563, 114, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (564, 284, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (565, 284, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (566, 284, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (567, 284, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (568, 261, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (569, 261, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (570, 261, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (571, 261, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (572, 301, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (573, 301, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (574, 301, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (575, 301, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (576, 203, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (577, 203, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (578, 203, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (579, 203, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (580, 221, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (581, 221, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (582, 221, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (583, 221, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (584, 335, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (585, 335, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (586, 335, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (587, 335, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (588, 194, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (589, 194, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (590, 194, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (591, 194, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (592, 400, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (593, 400, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (594, 400, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (595, 400, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (596, 305, "10GY1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (597, 305, "10CE2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (598, 305, "10HY3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (599, 305, "10GP1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (600, 232, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (601, 232, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (602, 232, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (603, 232, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (604, 395, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (605, 395, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (606, 395, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (607, 395, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (608, 146, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (609, 146, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (610, 146, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (611, 146, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (612, 240, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (613, 240, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (614, 240, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (615, 240, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (616, 297, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (617, 297, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (618, 297, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (619, 297, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (620, 361, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (621, 361, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (622, 361, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (623, 361, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (624, 287, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (625, 287, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (626, 287, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (627, 287, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (628, 159, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (629, 159, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (630, 159, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (631, 159, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (632, 191, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (633, 191, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (634, 191, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (635, 191, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (636, 161, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (637, 161, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (638, 161, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (639, 161, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (640, 310, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (641, 310, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (642, 310, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (643, 310, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (644, 145, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (645, 145, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (646, 145, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (647, 145, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (648, 380, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (649, 380, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (650, 380, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (651, 380, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (652, 348, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (653, 348, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (654, 348, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (655, 348, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (656, 197, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (657, 197, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (658, 197, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (659, 197, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (660, 387, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (661, 387, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (662, 387, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (663, 387, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (664, 242, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (665, 242, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (666, 242, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (667, 242, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (668, 329, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (669, 329, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (670, 329, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (671, 329, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (672, 243, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (673, 243, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (674, 243, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (675, 243, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (676, 171, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (677, 171, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (678, 171, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (679, 171, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (680, 102, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (681, 102, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (682, 102, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (683, 102, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (684, 339, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (685, 339, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (686, 339, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (687, 339, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (688, 382, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (689, 382, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (690, 382, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (691, 382, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (692, 182, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (693, 182, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (694, 182, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (695, 182, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (696, 365, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (697, 365, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (698, 365, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (699, 365, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (700, 248, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (701, 248, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (702, 248, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (703, 248, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (704, 364, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (705, 364, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (706, 364, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (707, 364, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (708, 377, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (709, 377, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (710, 377, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (711, 377, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (712, 259, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (713, 259, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (714, 259, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (715, 259, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (716, 257, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (717, 257, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (718, 257, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (719, 257, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (720, 311, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (721, 311, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (722, 311, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (723, 311, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (724, 341, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (725, 341, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (726, 341, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (727, 341, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (728, 101, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (729, 101, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (730, 101, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (731, 101, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (732, 236, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (733, 236, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (734, 236, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (735, 236, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (736, 165, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (737, 165, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (738, 165, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (739, 165, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (740, 396, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (741, 396, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (742, 396, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (743, 396, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (744, 122, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (745, 122, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (746, 122, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (747, 122, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (748, 174, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (749, 174, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (750, 174, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (751, 174, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (752, 328, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (753, 328, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (754, 328, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (755, 328, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (756, 298, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (757, 298, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (758, 298, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (759, 298, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (760, 323, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (761, 323, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (762, 323, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (763, 323, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (764, 216, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (765, 216, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (766, 216, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (767, 216, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (768, 334, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (769, 334, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (770, 334, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (771, 334, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (772, 123, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (773, 123, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (774, 123, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (775, 123, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (776, 372, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (777, 372, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (778, 372, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (779, 372, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (780, 342, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (781, 342, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (782, 342, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (783, 342, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (784, 294, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (785, 294, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (786, 294, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (787, 294, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (788, 269, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (789, 269, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (790, 269, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (791, 269, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (792, 273, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (793, 273, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (794, 273, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (795, 273, "10APH4")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (796, 241, "10CH1")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (797, 241, "10BY2")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (798, 241, "10PH3")''')
cursor.execute('''INSERT INTO Enrolments (ID, studentID, classID) VALUES (799, 241, "10APH4")''')
print('finish inserting data into Enrolments table<br />')
print('start inserting data into Students table<br />')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (169, "Cale Padilla")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (135, "Aubree Gordon")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (138, "Kendrick Holt")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (249, "Elliott Chaney")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (229, "Ryker Pace")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (299, "Deven Chapman")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (393, "Brogan Barrett")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (103, "Mathew Lester")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (397, "Matias Roman")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (226, "Holden Wu")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (367, "Israel Benson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (156, "Victor Munoz")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (344, "Fisher Hutchinson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (228, "Donte Faulkner")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (333, "Kody Hayden")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (272, "Delaney Hunter")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (370, "Jamya Avila")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (213, "Justine Chung")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (239, "Savanah Herring")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (231, "Dillan Simon")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (172, "Hallie Henson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (237, "Tyree Bolton")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (309, "Jaidyn Cervantes")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (250, "Jadyn Klein")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (290, "Chanel Mcpherson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (383, "Lizbeth Kramer")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (265, "Greta Robbins")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (356, "Nikolas Rollins")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (374, "Amiah Ashley")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (115, "Liberty Mccall")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (324, "Sage Sutton")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (162, "Jerry Freeman")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (306, "Jordyn Downs")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (276, "Laila Bennett")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (391, "Matilda Juarez")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (268, "Anaya Dominguez")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (107, "Steve Guzman")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (363, "Kyra Russell")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (267, "Kara Walker")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (330, "Lina Holden")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (282, "Veronica Haley")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (227, "Donavan Bryan")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (278, "Savanna Novak")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (313, "Zoe Stout")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (258, "Beckham Maldonado")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (337, "Lailah Marshall")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (136, "Gabriela Hernandez")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (148, "Trystan Benjamin")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (140, "Lilah Church")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (192, "Conor Bell")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (398, "Angie York")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (386, "Santino Mcmillan")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (128, "Miah Clark")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (164, "Ireland Mahoney")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (149, "Cora Lawrence")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (327, "Jenny Kirk")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (384, "Alexander Rivas")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (252, "Jovanny Rodgers")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (319, "Juan Curtis")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (175, "Melissa Horton")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (318, "Adrienne Werner")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (210, "Skyler Roberson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (280, "Ava Aguirre")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (362, "Chana Pineda")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (199, "Zane Price")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (168, "Augustus Castro")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (206, "Lane Carpenter")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (315, "Terrell Acosta")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (132, "Gael Vaughn")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (152, "Leon Barry")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (225, "Dakota Burke")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (205, "Victoria Williams")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (215, "Lewis Forbes")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (233, "Lyric Petty")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (291, "Alexa Chang")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (113, "Marquis Case")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (186, "Monica Leblanc")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (375, "Callie Noble")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (104, "Alayna May")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (271, "Mila Day")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (279, "Landin Merritt")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (358, "Dylan Boone")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (212, "Cooper Sexton")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (369, "Madalynn Carey")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (274, "Miya Mack")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (345, "Kallie Harding")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (388, "Kirsten Mccarthy")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (154, "Elaina Hart")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (373, "Adam Lutz")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (394, "Areli Braun")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (141, "Kamryn Clements")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (262, "Harper Briggs")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (399, "Santos Riggs")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (352, "Elias Luna")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (188, "Yael Cameron")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (389, "Javier Wilson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (217, "Adriana Becker")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (283, "Jaime Abbott")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (142, "Armani Short")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (100, "Dean Reese")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (119, "Darren Macias")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (256, "Courtney Webster")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (211, "Allie Estes")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (224, "Alivia Boyd")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (116, "Jasper Lyons")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (163, "Darian Mclaughlin")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (246, "Leia Arnold")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (331, "Ana Lucero")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (177, "Naomi Frey")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (253, "Jakob Chan")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (260, "Justus Hines")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (300, "Wendy Pruitt")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (218, "Sebastian Bartlett")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (332, "Alfred Shields")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (326, "Rylee Hudson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (270, "Malia Flynn")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (343, "Jordon Miles")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (281, "Kaia Mann")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (118, "Madison Mendoza")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (351, "Collin Hess")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (350, "Emelia Vance")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (153, "Manuel Saunders")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (312, "Luna Gomez")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (320, "Ari Liu")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (121, "Malakai Ball")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (179, "Aryanna Mcconnell")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (359, "Milo Stephens")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (214, "Leanna Perry")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (303, "Hezekiah Hester")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (167, "Zara Carlson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (317, "Omar Reyes")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (134, "Nayeli Vasquez")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (354, "Yareli Krueger")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (158, "Bailey Dean")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (347, "Malik Cummings")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (151, "Hayden Hill")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (314, "Ruben Flowers")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (385, "Gerardo Mcfarland")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (263, "Dominique Mullins")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (381, "Noah Ortiz")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (114, "Draven Villegas")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (284, "Morgan Edwards")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (261, "Walker Humphrey")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (301, "Andrea Velez")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (203, "Tiara Larson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (221, "Luz Beltran")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (335, "Trevor Anthony")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (194, "Griffin Cox")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (400, "Gregory Wilkerson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (305, "Jayson Andersen")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (232, "Milagros Bender")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (395, "Ryleigh Mercado")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (146, "Jagger Mcknight")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (240, "Marlon Mccullough")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (297, "Katelyn Frazier")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (361, "Keshawn Craig")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (287, "Danica Huynh")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (159, "Barbara Michael")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (191, "Phillip Farmer")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (161, "Josiah Koch")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (310, "Meadow Underwood")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (145, "Jamal Ross")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (380, "Cynthia Moreno")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (348, "Kristen Wallace")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (197, "Yaritza Webb")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (387, "Wayne Jacobson")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (242, "Charles Mueller")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (329, "Jaron Burgess")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (243, "Will Daugherty")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (171, "Patricia Alvarado")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (102, "Boston Walters")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (339, "Jermaine Davies")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (382, "Marley Glenn")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (182, "Marc Arias")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (365, "Drake George")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (248, "Randy Villa")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (364, "Aydin Valdez")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (377, "Bailee Murillo")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (259, "Branden Stafford")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (257, "Shawn Hobbs")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (311, "Dennis Hurst")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (341, "Denisse Wiggins")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (101, "Guillermo Holder")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (236, "Alisha Snow")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (165, "Maximo Reed")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (396, "Kylan Mora")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (122, "Vicente Moon")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (174, "Bryanna Mcmahon")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (328, "Harper Li")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (298, "Keaton Jones")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (323, "Alexus Lee")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (216, "Levi Matthews")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (334, "Dashawn Massey")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (123, "Cordell Brock")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (372, "Davin Beck")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (342, "Bruno Jenkins")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (294, "Tristan Lynn")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (269, "Isaias Zuniga")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (273, "Rachael Cuevas")''')
cursor.execute('''INSERT INTO Students (ID, name) VALUES (241, "Joy Peterson")''')
print('finish inserting data into Students table<br />')
conn.commit()
cursor.close()